services:
  pocketbase:
    image: pocketbase
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_data:/pb/pb_data
    command: ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
