services:
  database:
    image: postgis/postgis:16-3.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgesql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  cache:
    image: redis:latest

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extension:/directus/extension
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_healthy
        restart: true
    env_file:
      - directus.env
